parque.capacidad.maxima=100
parque.turistas.iniciales=40
parque.dinosaurios.carnivoros=8
parque.dinosaurios.herbivoros=15
parque.trabajadores=12
parque.vehiculos=5
parque.vehiculos.pasos.reparacion=4

parque.energia.inicial=1000
parque.energia.consumo.paso=25
parque.energia.minima.operacion=100

parque.precio.boleto=250.00
parque.precio.souvenir=180.00
parque.precio.spa=350.00
parque.precio.observacion=120.00
parque.costo.mantenimiento=500.00
parque.costo.energia.unidad=2.50
parque.costo.reparacion.vehiculo=800.00

parque.sanitarios.capacidad=10
parque.observatorio.capacidad=15

parque.simulacion.pasos=20
parque.simulacion.intervalo.monitoreo=1
parque.simulacion.probabilidad.evento=0.25

db.url=jdbc:postgresql://localhost:5432/parque_dinosaurios
db.usuario=postgres
db.contrasena=samuel19
db.driver=org.postgresql.Driver
